### ISSUE TITLE
LongBench evaluation codebase is missing

### ISSUE THREAD

**Issue by BirdChristopher** [DeepAuto-AI/hip-attention#18]
The README lists the commands to run longbench evaluation, but I cannot find the exact python scripts in your repo.

Cound you please share your longbench evaluation codebase?

**Comment by gmlwns2000** [comment]
Hi @BirdChristopher,

Thank you for trying to look in our HiP Attention!

Sorry, I forgot to link the benchmark repositories to README. Here are the links:

- [LongBench](https://github.com/gmlwns2000/LongBench-hip)
- [RULER](https://github.com/gmlwns2000/RULER-hip)

The results of the above two benchmark suites is in [our updated pre-print](https://arxiv.org/pdf/2406.09827)

I am currently working on the next release of HiP attention, which supports an extremely long context, so I added the following two benchmark sets.

- [InfiniteBench](https://github.com/gmlwns2000/InfiniteBench-hip)
- [LOFT](https://github.com/gmlwns2000/LOFT-hip)

If you have any trouble reproducing our results, please feel free to leave further comments in this thread.

**Comment by BirdChristopher** [comment]
Thank you for your response.  I'm trying to directly leverage the hip_attention api in my code like this:

```
query_states = self.q_proj(hidden_states)
key_states = self.k_proj(hidden_states)
value_states = self.v_proj(hidden_states)
query_states = query_states.view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
key_states = key_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)
value_states = value_states.view(bsz, q_len, self.num_key_value_heads, self.head_dim).transpose(1, 2)

cos, sin = self.rotary_emb(value_states, position_ids)

query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

# It essentially concat new key/value tensor with the history tensor.
if past_key_value is not None:
    key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, None)

  scale = 1 / (self.head_dim ** 0.5)
  attn_output, _ = hip_attention(
      # NOTE: **IMPORTANT** You have to scale Q before attention, because we did not implement softmax scaler... 
      q=query_states.transpose(1,2) * scale, 
      k=key_states.transpose(1,2),
      v=value_states.transpose(1,2),
      mask_k=K_BUDGET,
      block_size_q=64,
      block_size_k=2
  )
  print(attn_output.shape)
```

The tensor shape issue keeps showing no matter what param tensor shape is given, [bsz, q_len, n_head, dim] or [bsz, q_len, hidden_size]. Can you offer some tips about the input shape requirement?

**Comment by BirdChristopher** [comment]
```
import torch
from hip import (
    hip_attention,
    HiPAttentionArgs
)


query_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)
key_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)
value_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)

invoke_args = HiPAttentionArgs(
    mask_k = 512,
    block_size_q = 64,
    block_size_k = 2,
    block_stride_q = 2,
    block_stride_k = 1
)
scale = 1 / (128 ** 0.5)
# TODO: 这里能调，先不调。
attn_output, _ = hip_attention(
    # NOTE: **IMPORTANT** You have to scale Q before attention, because we did not implement softmax scaler... 
    q=query_states.transpose(1,2) * scale, 
    k=key_states.transpose(1,2),
    v=value_states.transpose(1,2),
    args = invoke_args
)

print(attn_output.shape)
```
I re-fetch code and use above snippet to conduct test, but an exception like this happened:
```
Traceback (most recent call last):
  File "/home/jxd/ttft_expr/hip-attention-main/test.py", line 21, in <module>
    attn_output, _ = hip_attention(
                     ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 6436, in hip_attention
    ) = hip_masking(
        ^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 6163, in hip_masking
    ) = masking_step_loop(
        ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 5495, in masking_step_loop
    ) = masking_iteration_draft(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 4086, in masking_iteration_draft
    masking_iteration_draft_cuda_fused[grid](
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 133, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/testing.py", line 103, in do_bench
    fn()
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 112, in kernel_call
    self.pre_hook(args)
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 64, in _pre_hook
    self.restore_copies = [args[i].clone() for i in self.restore_idx]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 64, in <listcomp>
    self.restore_copies = [args[i].clone() for i in self.restore_idx]
                           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'clone'
```

Is there anything I did wrong?

**Comment by BirdChristopher** [comment]
```
import torch
from hip import (
    hip_attention,
    HiPAttentionArgs
)


query_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)
key_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)
value_states = torch.randn([2, 16000, 32, 128]).to("cuda:1").to(torch.float16)

invoke_args = HiPAttentionArgs(
    mask_k = 512,
    block_size_q = 64,
    block_size_k = 2,
    block_stride_q = 2,
    block_stride_k = 1
)
scale = 1 / (128 ** 0.5)
attn_output, _ = hip_attention(
    # NOTE: **IMPORTANT** You have to scale Q before attention, because we did not implement softmax scaler... 
    q=query_states.transpose(1,2) * scale, 
    k=key_states.transpose(1,2),
    v=value_states.transpose(1,2),
    args = invoke_args
)

print(attn_output.shape)
```
I re-fetch code and use above snippet to conduct test, but an exception like this happened:
```
Traceback (most recent call last):
  File "/home/jxd/ttft_expr/hip-attention-main/test.py", line 21, in <module>
    attn_output, _ = hip_attention(
                     ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 6436, in hip_attention
    ) = hip_masking(
        ^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 6163, in hip_masking
    ) = masking_step_loop(
        ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 5495, in masking_step_loop
    ) = masking_iteration_draft(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/nvtx/nvtx.py", line 116, in inner
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jxd/ttft_expr/hip-attention-main/hip/models/hip_attention/attention2_draft_prefetch.py", line 4086, in masking_iteration_draft
    masking_iteration_draft_cuda_fused[grid](
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 133, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/testing.py", line 103, in do_bench
    fn()
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 112, in kernel_call
    self.pre_hook(args)
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 64, in _pre_hook
    self.restore_copies = [args[i].clone() for i in self.restore_idx]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/hip_attn/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 64, in <listcomp>
    self.restore_copies = [args[i].clone() for i in self.restore_idx]
                           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'clone'
```

Is there anything I did wrong?

**Comment by gmlwns2000** [comment]
Hi, @BirdChristopher ,

It is the Triton library bug. Triton autotuner has a bug in that it does not accept an optional tensor as a restore and reset target.
Therefore, you have to change the triton code in order to use the codebase. Here is the guide:

```diff
# triton/runtime/autotuner.py
# Line 69
- self.restore_copies = [args[i].clone() for i in self.restore_idx]
+ self.restore_copies = [args[i].clone() if args[i] is not None else None for i in self.restore_idx]
# Line 74
+ if args[j] is None: continue
    args[j].copy_(self.restore_copies[i])

```

Thanks!

**Comment by BirdChristopher** [comment]
Really appreciate your support and hip_attention is working correctly right now :) 👍

**Comment by gmlwns2000** [comment]
I am happy to hear that! If you have further problems or questions, please feel free to open new issues.
